# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminka.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db_data import db_session
from db_data.questions import Questions
import sqlite3


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(590, 645)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 591, 771))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.505382, y1:0.267, x2:0.506, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(248, 255, 247, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 571, 71))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 180, 571, 131))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 571, 21))
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 360, 571, 201))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 320, 571, 31))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(80, 580, 431, 51))
        self.pushButton.setStyleSheet("background-color: rgba(210, 220, 210, 150);\n"
"border: 1px solid rgba(210, 220, 210, 180);\n"
"border-radius: 10px;\n"
"color: black;\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton.clicked.connect(self.add)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#1a271a;\">Добавление вопросов в базу днных.</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#1a271a;\">Вопрос:</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#1a271a;\">Ответ:</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Добавить"))

    def add(self):
        db_session.global_init('db_data/questions.db')
        db_sess = db_session.create_session()
        qa = Questions()
        conn = sqlite3.connect('db_data/questions.db')
        cur = conn.cursor()
        qid = cur.execute("SELECT * FROM questions").fetchall()[-1][0]
        qa.quest = self.textEdit.toPlainText()
        qa.ans = self.textEdit.toPlainText()
        qa.id = qid + 1
        db_sess.add(qa)
        db_sess.commit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
